#!/bin/bash

sudo apt update && sudo apt upgrade -y
sudo apt install jq -y

# install docker
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io
docker version

# install docker-compose
VER=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep tag_name | cut -d '"' -f 4)

curl -L "https://github.com/docker/compose/releases/download/"$VER"/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

chmod +x /usr/local/bin/docker-compose
docker-compose --version

docker pull elixirprotocol/validator:v3

git clone https://github.com/fmsuicmc/elixir-metadata

read -p 'node ip : ' ip
read -p 'custom name : ' name
read -p 'wallet address : ' address
read -p 'wallet private key : ' privatekey

cd elixir-metadata
rm validator.env
touch validator.env
echo "ENV=testnet-3" >> validator.env
echo "" >> validator.env
echo "STRATEGY_EXECUTOR_IP_ADDRESS=$ip" >> validator.env
echo "STRATEGY_EXECUTOR_DISPLAY_NAME=$name" >> validator.env
echo "STRATEGY_EXECUTOR_BENEFICIARY=$address" >> validator.env
echo "SIGNER_PRIVATE_KEY=$privatekey" >> validator.env

docker run -it \
  --env-file $Home/root/elixir-metadata/validator.env \
  --name elixir \
  elixirprotocol/validator:v3
